eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    br:
      com:
        arithomazini:
          letscode:
            cardgamefilmes:
              client: DEBUG

